const SETTINGS_KEYS = {
  BOT_ENABLED: 'botEnabled',
  ARCHIVE_CHANNEL_ID: 'archiveChannelId',
  ARCHIVE_CHANNEL_USERNAME: 'archiveChannelUsername',
  CHARLES_USERNAME: 'charlesUsername',
  CHARLES_CHAT_ID: 'charlesChatId',
  CHRIS_USERNAME: 'chrisUsername',
  ONBOARDING_FORM_URL: 'onboardingFormUrl',
  BROKER_LINK_AUSTRALIA: 'brokerLinkAustralia',
  BROKER_LINK_OTHER: 'brokerLinkOther',
  LAST_NUDGE_SCAN_AT: 'lastNudgeScanAt',
};

const USER_STAGE = {
  IDLE: 'IDLE',
  S1_OPENING: 'S1_OPENING',
  S2_PITCH: 'S2_PITCH',
  S3_COUNTRY: 'S3_COUNTRY',
  S3_AU_NZ_INTRO: 'S3_AU_NZ_INTRO',
  S4_CAPITAL_GATE: 'S4_CAPITAL_GATE',
  S5_BROKER: 'S5_BROKER',
  S6_FUNDING: 'S6_FUNDING',
  S7_EMAIL: 'S7_EMAIL',
  S7_RETRY_EMAIL: 'S7_RETRY_EMAIL',
  S8_MT5: 'S8_MT5',
  S9_COMPLETE: 'S9_COMPLETE',
  PATH2_LIBRARY: 'PATH2_LIBRARY',
  FAQ: 'FAQ',
  HANDOFF_TO_CHARLES: 'HANDOFF_TO_CHARLES',
};

const USER_BUTTONS = {
  GET_STARTED: '🚀 Get Started',
  SEE_HOW: '🎬 See How It Works',
  FAQ: '❓ FAQ',
  SPEAK_TO_CHARLES: '💬 Speak to Charles',
  FIRST_TIME: '🙋 First time',
  TRADED_BEFORE: "📈 I've traded before",
  I_HAVE_A_QUESTION: '💬 I have a question',
  HAPPY_TO_CONTINUE: '✅ Yes, happy to continue',
  AUSTRALIA: '🇦🇺 Australia',
  EUROPE: '🇪🇺 Europe',
  NEW_ZEALAND: '🇳🇿 New Zealand',
  OTHER: '🌐 Other',
  CONTINUE: '▶ Continue',
  CHAT_WITH_CHRIS: '💬 Chat with Chris',
  CAPITAL_500_1000: '$500 - $1,000',
  CAPITAL_1000_5000: '$1,000 - $5,000',
  CAPITAL_5000_PLUS: '$5,000+',
  ACCOUNT_OPENED: '✅ Account opened',
  DEPOSIT_MADE: "✅ I've made my deposit",
  TRY_DIFFERENT_EMAIL: '🔄 Try a different email',
  DONE_FUNDS_TRANSFERRED: '✅ Done, funds transferred',
  IM_READY: "✅ I'm Ready",
  NEXT_VIDEO: '▶ Next Video',
  BACK_TO_MENU: '⬅ Back to Menu',
  BACK: '⬅ Back',
  RESTART: '🔄 Restart',
};

const ADMIN_BUTTONS = {
  OPEN: '🛠 Admin Panel',
  CONTENT: '📝 Content',
  MEDIA: '🎞 Media',
  SETTINGS: '⚙ Settings',
  ADMINS: '👮 Admins',
  USERS: '📊 Users',
  TOGGLE: '🔴 Disable Bot',
  ENABLE: '🟢 Enable Bot',
  USER_VIEW: '👤 User View',
  BACK: '⬅ Back',
  FLOW_TEXTS: '🧭 Flow Texts',
  NUDGE_TEXTS: '🔔 Nudge Texts',
  LINKS: '🔗 Links & Contacts',
  VOICE_NOTES: '🎙 Voice Notes',
  CORE_VIDEOS: '🎬 Core Videos',
  FAQ_VIDEOS: '❓ FAQ Videos',
  PATH2_VIDEOS: '🎥 Path 2 Videos',
  TIER_CARDS: '🖼 Tier Cards',
  NUDGE_MEDIA: '📣 Nudge Media',
  SET_FILE_CHANNEL: '📺 Set File Channel',
  TYPE_CHANNEL_ID: '⌨ Type Channel ID',
  ADD_ADMIN: '➕ Add Admin',
  REMOVE_ADMIN: '➖ Remove Admin',
  LIST_ADMINS: '📜 List Admins',
  LIST_USERS: '📋 List Users',
};

const ADMIN_SETTING_OPTIONS = [
  { key: SETTINGS_KEYS.CHARLES_USERNAME, label: 'Charles Username' },
  { key: SETTINGS_KEYS.CHARLES_CHAT_ID, label: 'Charles Chat ID' },
  { key: SETTINGS_KEYS.CHRIS_USERNAME, label: 'Chris Username' },
  { key: SETTINGS_KEYS.ONBOARDING_FORM_URL, label: 'Onboarding Form URL' },
  { key: SETTINGS_KEYS.BROKER_LINK_AUSTRALIA, label: 'Broker Link - Australia' },
  { key: SETTINGS_KEYS.BROKER_LINK_OTHER, label: 'Broker Link - Other Countries' },
];

const LIBRARY_VIDEOS = [
  { key: 'path2_video_1', label: '1. How the System Works' },
  { key: 'path2_video_2', label: '2. Why Automation Beats Bots' },
  { key: 'path2_video_3', label: '3. Your Money Is Always Yours' },
  { key: 'path2_video_4', label: '4. The Free Trial Explained' },
  { key: 'path2_video_5', label: '5. Why Most People Fail at Trading' },
  { key: 'path2_video_6', label: '6. Why Emotion Kills Trading' },
  { key: 'path2_video_7', label: "7. Charles's Story" },
  { key: 'path2_video_8', label: '8. Why We Do This' },
];

const FAQ_VIDEOS = [
  { key: 'faq_returns', label: '💰 What returns can I expect?' },
  { key: 'faq_safe', label: '🔒 Is my money safe?' },
  { key: 'faq_withdraw', label: '💸 Can I withdraw anytime?' },
  { key: 'faq_trial', label: '🎯 How does the trial work?' },
  { key: 'faq_experience', label: '💡 Do I need experience?' },
  { key: 'faq_minimum', label: "💵 What's the minimum?" },
  { key: 'faq_bot', label: '🤖 Is it a bot?' },
  { key: 'faq_trade', label: '📊 What do you trade?' },
  { key: 'faq_funded', label: '🏦 Can I use a funded account?' },
  { key: 'faq_lot_sizes', label: '📏 How do lot sizes work?' },
];

const ASSET_DEFINITIONS = [
  { key: 's1_opening_voice', group: 'voice_notes', label: 'S1 Voice Note', kind: 'voice' },
  { key: 's5_charles_voice', group: 'voice_notes', label: 'S5 Charles Voice Note', kind: 'voice' },
  { key: 's9_onboarding_voice', group: 'voice_notes', label: 'S9 Onboarding Voice Note', kind: 'voice' },
  { key: 's5_intro_video', group: 'core_videos', label: 'S5 Intro Broker Video', kind: 'video' },
  { key: 's6_funding_video', group: 'core_videos', label: 'S6 Funding Video', kind: 'video' },
  { key: 's8_mt5_video', group: 'core_videos', label: 'S8 MT5 Setup Video', kind: 'video' },
  { key: 'tier_card_500_1000', group: 'tier_cards', label: 'Tier Card $500-$1,000', kind: 'photo' },
  { key: 'tier_card_1000_5000', group: 'tier_cards', label: 'Tier Card $1,000-$5,000', kind: 'photo' },
  { key: 'tier_card_5000_plus', group: 'tier_cards', label: 'Tier Card $5,000+', kind: 'photo' },
  { key: 'nudge1_voice', group: 'nudge_media', label: 'Nudge 1 Voice', kind: 'voice' },
  { key: 'nudge2_aus_voice', group: 'nudge_media', label: 'Nudge 2 AUS Voice', kind: 'voice' },
  { key: 'nudge2_global_voice', group: 'nudge_media', label: 'Nudge 2 Global Voice', kind: 'voice' },
  { key: 'nudge3_chris_video', group: 'nudge_media', label: 'Nudge 3 Chris Testimonial Video', kind: 'video' },
  { key: 'nudge4_voice', group: 'nudge_media', label: 'Nudge 4 Voice', kind: 'voice' },
  { key: 'nudge5_voice', group: 'nudge_media', label: 'Nudge 5 Voice', kind: 'voice' },
  ...LIBRARY_VIDEOS.map((item) => ({ ...item, group: 'path2_videos', kind: 'video' })),
  ...FAQ_VIDEOS.map((item) => ({ ...item, group: 'faq_videos', kind: 'video' })),
];

const DEFAULT_SETTINGS = {
  [SETTINGS_KEYS.BOT_ENABLED]: true,
  [SETTINGS_KEYS.ARCHIVE_CHANNEL_ID]: null,
  [SETTINGS_KEYS.ARCHIVE_CHANNEL_USERNAME]: null,
  [SETTINGS_KEYS.CHARLES_USERNAME]: 'AlphaSightGlobal',
  [SETTINGS_KEYS.CHARLES_CHAT_ID]: null,
  [SETTINGS_KEYS.CHRIS_USERNAME]: 'Griffo1324',
  [SETTINGS_KEYS.ONBOARDING_FORM_URL]: 'https://alphasightcapital.framer.website/onboarding',
  [SETTINGS_KEYS.BROKER_LINK_AUSTRALIA]: 'https://affiliate.marketsvox.com/visit/?bta=35089&brand=marketsvox&campaign=2D438D39-442A-4F11-BB37-7FE0F43C537A',
  [SETTINGS_KEYS.BROKER_LINK_OTHER]: 'https://affiliate.marketsvox.com/visit/?bta=35089&brand=marketsvox&campaign=2D438D39-442A-4F11-BB37-7FE0F43C537A',
  [SETTINGS_KEYS.LAST_NUDGE_SCAN_AT]: null,
};

const DEFAULT_TEMPLATES = [
  { key: 'library_menu_intro', group: 'flow', label: 'Path 2 Library Intro', value: "Want to see exactly how it works before getting started?\n\n8 short videos, everything you need to know. Watch in any order and come back anytime.\n\nTap a video to watch." },
  { key: 's2_first_time_pitch', group: 'flow', label: 'S2 Path A - Text Message', value: "Brilliant, most of our members started with zero experience and that's exactly who the system is built for. You don't need to know anything about trading to see great results.\n\nWe trade forex on our own accounts every day. Our software automatically mirrors every trade directly to yours in real time, completely hands-free.\n\nYour money stays in your own trading account the whole time. Only you have access to it, we physically cannot touch it.\n\nWe're running a 3-month free trial right now, you make real returns for 3 months before paying anything. After that it's just $29.99 a month, easily covered by your returns. Cancel anytime.\n\nWould you be happy to continue after the trial if you're seeing consistent results?" },
  { key: 's2_traded_pitch', group: 'flow', label: 'S2 Path B - Text Message', value: "Even better, having a bit of experience means you'll understand straight away how this works and why the results are so consistent.\n\nWe trade forex on our own accounts every day. Our software automatically mirrors every trade directly to yours in real time, completely hands-free.\n\nYour money stays in your own trading account the whole time. Only you have access to it, we physically cannot touch it.\n\nWe're running a 3-month free trial right now, you make real returns for 3 months before paying anything. After that it's just $29.99 a month, easily covered by your returns. Cancel anytime.\n\nWould you be happy to continue after the trial if you're seeing consistent results?" },
  { key: 's3_country_prompt', group: 'flow', label: 'S3 Country Confirmation - Text Message', value: "Quick one, what country are you based in? Makes a difference for the deposit instructions I'll send you." },
  { key: 's3_au_nz_intro', group: 'flow', label: 'S3 AUS / NZ Only - Text Message', value: "One thing worth knowing, we have a dedicated Australian rep, Chris Griffin, who's been investing with us for a while and even brought his sons on board. If you'd like to speak to a fellow Australian before getting started, Chris is always happy to chat.\n\nTap below to continue or reach out to Chris directly, completely up to you." },
  { key: 's4_capital_gate', group: 'flow', label: 'S4 Capital Gate - Text Message', value: "Before I send you the account details, what sort of starting amount did you have in mind?" },
  { key: 's4_below_minimum', group: 'flow', label: 'S4 Below Minimum', value: "Our minimum is $500 USD / $800 AUD. That's the floor for the system to trade properly. If that changes later, the door is open and we'd love to help you." },
  { key: 's4_caption_500_1000', group: 'flow', label: 'S4 Caption $500-$1,000', value: "Good shout. Most people start here to see month one, then add more once they've seen the results." },
  { key: 's4_caption_1000_5000', group: 'flow', label: 'S4 Caption $1,000-$5,000', value: "Nice one. At this level the system has more room to work, you'll see stronger results from day one." },
  { key: 's4_caption_5000_plus', group: 'flow', label: 'S4 Caption $5,000+', value: "Love that. At this level the system is running at full capacity from day one, you're going to see great results." },
  { key: 's5_aus_text', group: 'flow', label: 'S5 Australia Text', value: "Here's the link to open your trading account:\n\n{{brokerLink}}\n\nImportant before you deposit: Australian banks almost always block the first card attempt. Standard banking policy for international brokers, nothing to do with MarketsVox. Every single AUS member hits this.\n\nBest options:\n- Skrill (recommended)\n- Bank wire\n- Cryptocurrency\n\nOnce you've opened the account, let me know." },
  { key: 's5_global_text', group: 'flow', label: 'S5 Global Text', value: "Here's the link to open your trading account:\n\n{{brokerLink}}\n\nOnce you've opened the account, let me know and I'll walk you through the next step." },
  { key: 's6_text', group: 'flow', label: 'S6 Funding Text', value: "Watch that first, it'll walk you through exactly how to add your investment.\n\nOnce you've made your deposit, tap below." },
  { key: 's7_prompt', group: 'flow', label: 'S7 Email Prompt', value: "Nice one. Drop me the email address you used to register and we'll get you confirmed on the system straight away." },
  { key: 's7_confirmed', group: 'flow', label: 'S7 Confirmed Outcome', value: "You're confirmed on the system.\n\nOne last step, let's get your MT5 trading account set up so we can connect everything." },
  { key: 's7_not_found_first', group: 'flow', label: 'S7 Not Found First', value: "Hmm, we couldn't find a registration under that email. Could just be a typo, worth double checking.\n\nWant to try a different email or speak to Charles directly?" },
  { key: 's7_not_found_second', group: 'flow', label: 'S7 Not Found Second', value: "No worries at all, Charles will get you sorted straight away. Tap below." },
  { key: 's7_email_already_used', group: 'flow', label: 'S7 Email Already Used', value: "Sorry. that email has been used by someone else.\nCould just be a typo, worth double checking.\n\nPlease send me a different email, the one you used to register and we'll get you confirmed on the system straight away." },
  { key: 'past_stage_notice', group: 'flow', label: 'Past Stage Notice', value: "You're already past that step.\n\nUse the buttons below to continue, or tap Restart if you'd like to begin again." },
  { key: 's8_text', group: 'flow', label: 'S8 MT5 Text', value: "Brilliant, nearly there.\n\nLast step before you're fully connected, set up your MT5 CENT trading account inside MarketsVox. Takes about 2 minutes.\n\nSteps:\n1. Log into your MarketsVox account\n2. Go to Trading Accounts -> New Real\n3. Select Standard 500\n4. Set your profile password\n5. Hit Submit\n6. Check your email  MT5 credentials will arrive there\n\nOnce you've transferred your funds to the CENT account, tap below." },
  { key: 's9_text', group: 'flow', label: 'S9 Completion Text', value: "Welcome to the team.\n\nOne last step, please fill in your details below so we can connect your account to the system:\n\n{{onboardingFormUrl}}\n\nTakes about 2 minutes. Once you submit you'll be connected with our support team who will get everything set up for you." },
  { key: 'nudge3_text', group: 'nudge', label: 'Nudge 3 Text', value: "While you're getting sorted this is Chris, our Australian rep. He started exactly where you are.\n\nChris has been investing with us for a while, referred both of his sons, and is now part of the team helping Australian and New Zealand members get the most out of the system.\n\nOnce your deposit is in we can get you started." },
];

module.exports = {
  SETTINGS_KEYS,
  USER_STAGE,
  USER_BUTTONS,
  ADMIN_BUTTONS,
  ADMIN_SETTING_OPTIONS,
  LIBRARY_VIDEOS,
  FAQ_VIDEOS,
  ASSET_DEFINITIONS,
  DEFAULT_SETTINGS,
  DEFAULT_TEMPLATES,
};
